# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: PHP Code Style (phpcs)
        # uses: chindit/actions-phpcs@ccda708ed581ebe13a66497cc47c07b8346af3b3
        uses: chindit/actions-phpcs@1.0.1
        with:
          dir: .
