# This is a basic workflow to help you get started with Actions

name: PHP - Code and Security

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Security Check
        uses: StephaneBour/actions-php-security-checker@1.1
        with:
          composer-lock: './composer.lock'
          
      - name: Code Style
        uses: chindit/actions-phpcs@master
        with:
          dir: src/
